export default [
  {"id": "iPhone1,1", "displayId": 1, "name": "iPhone"},
  {"id": "iPhone1,2", "displayId": 1, "name": "iPhone 3G"},
  {"id": "iPhone2,1", "displayId": 1, "name": "iPhone 3GS"},
  {"id": "iPhone3,1", "displayId": 2, "name": "iPhone 4 (GSM)"},
  {"id": "iPhone3,3", "displayId": 2, "name": "iPhone 4 (CDMA)"},
  {"id": "iPhone4,1", "displayId": 2, "name": "iPhone 4S"},
  {"id": "iPhone5,1", "displayId": 3, "name": "iPhone 5 (A1428)"},
  {"id": "iPhone5,2", "displayId": 3, "name": "iPhone 5 (A1429)"},
  {"id": "iPhone5,3", "displayId": 3, "name": "iPhone 5c (A1456/A1532)"},
  {"id": "iPhone5,4", "displayId": 3, "name": "iPhone 5c (A1507/A1516/A1529)"},
  {"id": "iPhone6,1", "displayId": 3, "name": "iPhone 5s (A1433/A1453)"},
  {"id": "iPhone6,2", "displayId": 3, "name": "iPhone 5s (A1457/A1518/A1530)"},
  {"id": "iPhone7,1", "displayId": 1, "name": "iPhone 6 Plus"},
  {"id": "iPhone7,2", "displayId": 1, "name": "iPhone 6"},
  {"id": "iPhone8,1", "displayId": 1, "name": "iPhone 6s"},
  {"id": "iPhone8,2", "displayId": 1, "name": "iPhone 6s Plus"},
  {"id": "iPad1,1", "displayId": 1, "name": "iPad"},
  {"id": "iPad2,1", "displayId": 1, "name": "iPad 2 (Wi-Fi)"},
  {"id": "iPad2,2", "displayId": 1, "name": "iPad 2 (GSM)"},
  {"id": "iPad2,3", "displayId": 1, "name": "iPad 2 (CDMA)"},
  {"id": "iPad2,4", "displayId": 1, "name": "iPad 2 (Wi-Fi, revised)"},
  {"id": "iPad2,5", "displayId": 1, "name": "iPad mini (Wi-Fi)"},
  {"id": "iPad2,6", "displayId": 1, "name": "iPad mini (A1454)"},
  {"id": "iPad2,7", "displayId": 1, "name": "iPad mini (A1455)"},
  {"id": "iPad3,1", "displayId": 1, "name": "iPad (3rd gen, Wi-Fi)"},
  {"id": "iPad3,2", "displayId": 1, "name": "iPad (3rd gen, Wi-Fi+LTE Verizon)"},
  {"id": "iPad3,3", "displayId": 1, "name": "iPad (3rd gen, Wi-Fi+LTE AT&T)"},
  {"id": "iPad3,4", "displayId": 1, "name": "iPad (4th gen, Wi-Fi)"},
  {"id": "iPad3,5", "displayId": 1, "name": "iPad (4th gen, A1459)"},
  {"id": "iPad3,6", "displayId": 1, "name": "iPad (4th gen, A1460)"},
  {"id": "iPad4,1", "displayId": 1, "name": "iPad Air (Wi-Fi)"},
  {"id": "iPad4,2", "displayId": 1, "name": "iPad Air (Wi-Fi+LTE)"},
  {"id": "iPad4,3", "displayId": 1, "name": "iPad Air (Rev)"},
  {"id": "iPad4,4", "displayId": 1, "name": "iPad mini 2 (Wi-Fi)"},
  {"id": "iPad4,5", "displayId": 1, "name": "iPad mini 2 (Wi-Fi+LTE)"},
  {"id": "iPad4,6", "displayId": 1, "name": "iPad mini 2 (Rev)"},
  {"id": "iPad4,7", "displayId": 1, "name": "iPad mini 3 (Wi-Fi)"},
  {"id": "iPad4,8", "displayId": 1, "name": "iPad mini 3 (A1600)"},
  {"id": "iPad4,9", "displayId": 1, "name": "iPad mini 3 (A1601)"},
  {"id": "iPad5,1", "displayId": 1, "name": "iPad mini 4 (Wi-Fi)"},
  {"id": "iPad5,2", "displayId": 1, "name": "iPad mini 4 (Wi-Fi+LTE)"},
  {"id": "iPad5,3", "displayId": 1, "name": "iPad Air 2 (Wi-Fi)"},
  {"id": "iPad5,4", "displayId": 1, "name": "iPad Air 2 (Wi-Fi+LTE)"},
  {"id": "iPod1,1", "displayId": 1, "name": "iPod touch"},
  {"id": "iPod2,1", "displayId": 1, "name": "iPod touch (2nd gen)"},
  {"id": "iPod3,1", "displayId": 1, "name": "iPod touch (3rd gen)"},
  {"id": "iPod4,1", "displayId": 1, "name": "iPod touch (4th gen)"},
  {"id": "iPod5,1", "displayId": 1, "name": "iPod touch (5th gen)"},
  {"id": "iPod7,1", "displayId": 1, "name": "iPod touch (6th gen)"}
];
